// Code generated by ent, DO NOT EDIT.

package rate

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the rate types in the database.
	Label = "rate"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldRateID holds the string denoting the rate_id field in the database.
	FieldRateID = "rate_id"
	// FieldReaction holds the string denoting the reaction field in the database.
	FieldReaction = "reaction"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeTweet holds the string denoting the tweet edge name in mutations.
	EdgeTweet = "tweet"
	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// Table holds the table name of the rate in the database.
	Table = "rates"
	// TweetTable is the table that holds the tweet relation/edge.
	TweetTable = "rates"
	// TweetInverseTable is the table name for the Tweet entity.
	// It exists in this package in order to avoid circular dependency with the "tweet" package.
	TweetInverseTable = "tweets"
	// TweetColumn is the table column denoting the tweet relation/edge.
	TweetColumn = "tweet_rates"
	// UserTable is the table that holds the user relation/edge.
	UserTable = "rates"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "user_rates"
)

// Columns holds all SQL columns for rate fields.
var Columns = []string{
	FieldID,
	FieldRateID,
	FieldReaction,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "rates"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"tweet_rates",
	"user_rates",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// Reaction defines the types for the "reaction" enum field.
type Reaction string

// Reaction values.
const (
	ReactionLike  Reaction = "like"
	ReactionFunny Reaction = "funny"
	ReactionLove  Reaction = "love"
	ReactionSad   Reaction = "sad"
)

func (r Reaction) String() string {
	return string(r)
}

// ReactionValidator is a validator for the "reaction" field enum values. It is called by the builders before save.
func ReactionValidator(r Reaction) error {
	switch r {
	case ReactionLike, ReactionFunny, ReactionLove, ReactionSad:
		return nil
	default:
		return fmt.Errorf("rate: invalid enum value for reaction field: %q", r)
	}
}

// OrderOption defines the ordering options for the Rate queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByRateID orders the results by the rate_id field.
func ByRateID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRateID, opts...).ToFunc()
}

// ByReaction orders the results by the reaction field.
func ByReaction(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReaction, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByTweetField orders the results by tweet field.
func ByTweetField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTweetStep(), sql.OrderByField(field, opts...))
	}
}

// ByUserField orders the results by user field.
func ByUserField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUserStep(), sql.OrderByField(field, opts...))
	}
}
func newTweetStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(TweetInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, TweetTable, TweetColumn),
	)
}
func newUserStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UserInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
	)
}
