// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"
	"twix/ent/rate"
	"twix/ent/tweet"
	"twix/ent/user"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// Rate is the model entity for the Rate schema.
type Rate struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// RateID holds the value of the "rate_id" field.
	RateID *uuid.UUID `json:"rate_id,omitempty"`
	// Reaction holds the value of the "reaction" field.
	Reaction rate.Reaction `json:"reaction,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the RateQuery when eager-loading is set.
	Edges        RateEdges `json:"edges"`
	tweet_rates  *int
	user_rates   *int
	selectValues sql.SelectValues
}

// RateEdges holds the relations/edges for other nodes in the graph.
type RateEdges struct {
	// Tweet holds the value of the tweet edge.
	Tweet *Tweet `json:"tweet,omitempty"`
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// loadedTypes holds the information for reporting if a
	// types was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// TweetOrErr returns the Tweet value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e RateEdges) TweetOrErr() (*Tweet, error) {
	if e.Tweet != nil {
		return e.Tweet, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: tweet.Label}
	}
	return nil, &NotLoadedError{edge: "tweet"}
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e RateEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Rate) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case rate.FieldID:
			values[i] = new(sql.NullInt64)
		case rate.FieldReaction:
			values[i] = new(sql.NullString)
		case rate.FieldCreatedAt, rate.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case rate.FieldRateID:
			values[i] = new(uuid.UUID)
		case rate.ForeignKeys[0]: // tweet_rates
			values[i] = new(sql.NullInt64)
		case rate.ForeignKeys[1]: // user_rates
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Rate fields.
func (r *Rate) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case rate.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected types %T for field id", value)
			}
			r.ID = int(value.Int64)
		case rate.FieldRateID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected types %T for field rate_id", values[i])
			} else if value != nil {
				r.RateID = value
			}
		case rate.FieldReaction:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected types %T for field reaction", values[i])
			} else if value.Valid {
				r.Reaction = rate.Reaction(value.String)
			}
		case rate.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected types %T for field created_at", values[i])
			} else if value.Valid {
				r.CreatedAt = value.Time
			}
		case rate.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected types %T for field updated_at", values[i])
			} else if value.Valid {
				r.UpdatedAt = value.Time
			}
		case rate.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected types %T for edge-field tweet_rates", value)
			} else if value.Valid {
				r.tweet_rates = new(int)
				*r.tweet_rates = int(value.Int64)
			}
		case rate.ForeignKeys[1]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected types %T for edge-field user_rates", value)
			} else if value.Valid {
				r.user_rates = new(int)
				*r.user_rates = int(value.Int64)
			}
		default:
			r.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Rate.
// This includes values selected through modifiers, order, etc.
func (r *Rate) Value(name string) (ent.Value, error) {
	return r.selectValues.Get(name)
}

// QueryTweet queries the "tweet" edge of the Rate entity.
func (r *Rate) QueryTweet() *TweetQuery {
	return NewRateClient(r.config).QueryTweet(r)
}

// QueryUser queries the "user" edge of the Rate entity.
func (r *Rate) QueryUser() *UserQuery {
	return NewRateClient(r.config).QueryUser(r)
}

// Update returns a builder for updating this Rate.
// Note that you need to call Rate.Unwrap() before calling this method if this Rate
// was returned from a transaction, and the transaction was committed or rolled back.
func (r *Rate) Update() *RateUpdateOne {
	return NewRateClient(r.config).UpdateOne(r)
}

// Unwrap unwraps the Rate entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (r *Rate) Unwrap() *Rate {
	_tx, ok := r.config.driver.(*txDriver)
	if !ok {
		panic("ent: Rate is not a transactional entity")
	}
	r.config.driver = _tx.drv
	return r
}

// String implements the fmt.Stringer.
func (r *Rate) String() string {
	var builder strings.Builder
	builder.WriteString("Rate(")
	builder.WriteString(fmt.Sprintf("id=%v, ", r.ID))
	builder.WriteString("rate_id=")
	builder.WriteString(fmt.Sprintf("%v", r.RateID))
	builder.WriteString(", ")
	builder.WriteString("reaction=")
	builder.WriteString(fmt.Sprintf("%v", r.Reaction))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(r.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(r.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Rates is a parsable slice of Rate.
type Rates []*Rate
